adducts: ['+Na', '+H', '-H', 'neutral']

forcefield:
  type: gaff
  steps: 500

impact:
  shotsPerRot: 64
  convergence: 0.001
  nRuns: 64
  seed: 0

ccs:
  alpha: 27.9
  beta: 0.14
  calibration: {'+Na': {'m': 0.8282445757267285, 'b': 27.84924995258012},
                '+H':  {'m': 0.8419640859610955, 'b': 35.15260461418354},
                '-H':  {'m': 0.8659194583284285, 'b': 19.49230686446195},
                'neutral':  {'m': 1.0, 'b': 0.0}}

amber:
  cycles: 10
  nframes: 10
  low: 1.25e+06
  high: 1.45e+06

nwchem:
  dft_template: default
  shielding_template: default
  shifts: ['H', 'C']
  reference: {'C': {'mean': 187.614272, 'std': 0.043953},
              'H': {'mean': 31.694003, 'std': 0.009460}}
  solvent: DMSO

mobcal:
  params: default
  atomtypes: default
  exe: mobcal_cascade
